# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui_project.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputGB = QtWidgets.QGroupBox(self.centralwidget)
        self.inputGB.setObjectName("inputGB")
        self.gridLayout = QtWidgets.QGridLayout(self.inputGB)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.inputGB)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inputPoiShapefileLE = QtWidgets.QLineEdit(self.inputGB)
        self.inputPoiShapefileLE.setObjectName("inputPoiShapefileLE")
        self.gridLayout.addWidget(self.inputPoiShapefileLE, 1, 2, 1, 1)
        self.inputPolygonLE = QtWidgets.QLineEdit(self.inputGB)
        self.inputPolygonLE.setStatusTip("")
        self.inputPolygonLE.setWhatsThis("")
        self.inputPolygonLE.setObjectName("inputPolygonLE")
        self.gridLayout.addWidget(self.inputPolygonLE, 0, 2, 1, 1)
        self.inputPolygonTB = QtWidgets.QToolButton(self.inputGB)
        self.inputPolygonTB.setObjectName("inputPolygonTB")
        self.gridLayout.addWidget(self.inputPolygonTB, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.inputGB)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.inputPoiTB = QtWidgets.QToolButton(self.inputGB)
        self.inputPoiTB.setObjectName("inputPoiTB")
        self.gridLayout.addWidget(self.inputPoiTB, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.inputGB)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.countryQueryCB = QtWidgets.QComboBox(self.inputGB)
        self.countryQueryCB.setObjectName("countryQueryCB")
        self.countryQueryCB.addItem("")
        self.countryQueryCB.addItem("")
        self.countryQueryCB.addItem("")
        self.countryQueryCB.addItem("")
        self.countryQueryCB.addItem("")
        self.countryQueryCB.addItem("")
        self.countryQueryCB.addItem("")
        self.gridLayout.addWidget(self.countryQueryCB, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.inputGB)
        self.shopSelectorGB = QtWidgets.QGroupBox(self.centralwidget)
        self.shopSelectorGB.setObjectName("shopSelectorGB")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.shopSelectorGB)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.shopTypesCheckBox = QtWidgets.QCheckBox(self.shopSelectorGB)
        self.shopTypesCheckBox.setObjectName("shopTypesCheckBox")
        self.gridLayout_2.addWidget(self.shopTypesCheckBox, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.shopSelectorGB)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.shopTypesComboBox = QtWidgets.QComboBox(self.shopSelectorGB)
        self.shopTypesComboBox.setEditable(False)
        self.shopTypesComboBox.setObjectName("shopTypesComboBox")
        self.shopTypesComboBox.addItem("")
        self.shopTypesComboBox.addItem("")
        self.shopTypesComboBox.addItem("")
        self.shopTypesComboBox.addItem("")
        self.gridLayout_2.addWidget(self.shopTypesComboBox, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.shopSelectorGB, 0, QtCore.Qt.AlignVCenter)
        self.outputGB = QtWidgets.QGroupBox(self.centralwidget)
        self.outputGB.setObjectName("outputGB")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.outputGB)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputShapefileLE = QtWidgets.QLineEdit(self.outputGB)
        self.outputShapefileLE.setObjectName("outputShapefileLE")
        self.gridLayout_3.addWidget(self.outputShapefileLE, 0, 1, 1, 1)
        self.outputShapefileTB = QtWidgets.QToolButton(self.outputGB)
        self.outputShapefileTB.setObjectName("outputShapefileTB")
        self.gridLayout_3.addWidget(self.outputShapefileTB, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.outputGB)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.startPB = QtWidgets.QPushButton(self.outputGB)
        self.startPB.setObjectName("startPB")
        self.gridLayout_3.addWidget(self.startPB, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.outputGB)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDisable = QtWidgets.QAction(MainWindow)
        self.actionDisable.setObjectName("actionDisable")

        self.retranslateUi(MainWindow)
        self.shopTypesCheckBox.toggled['bool'].connect(self.shopTypesComboBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Central American Shop Finder"))
        self.inputGB.setTitle(_translate("MainWindow", "Input Options"))
        self.label.setText(_translate("MainWindow", "Input polygon shapefile:"))
        self.inputPoiShapefileLE.setToolTip(_translate("MainWindow", "Select the Points of Interest shapefile here."))
        self.inputPolygonLE.setToolTip(_translate("MainWindow", "Select the input countries shapefile here."))
        self.inputPolygonTB.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Input POI shapefile:"))
        self.inputPoiTB.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Target country:"))
        self.countryQueryCB.setToolTip(_translate("MainWindow", "This is the list of available countries."))
        self.countryQueryCB.setItemText(0, _translate("MainWindow", "El Salvador"))
        self.countryQueryCB.setItemText(1, _translate("MainWindow", "Belize"))
        self.countryQueryCB.setItemText(2, _translate("MainWindow", "Costa Rica"))
        self.countryQueryCB.setItemText(3, _translate("MainWindow", "Guatemala"))
        self.countryQueryCB.setItemText(4, _translate("MainWindow", "Honduras"))
        self.countryQueryCB.setItemText(5, _translate("MainWindow", "Nicaragua"))
        self.countryQueryCB.setItemText(6, _translate("MainWindow", "Panama"))
        self.shopSelectorGB.setTitle(_translate("MainWindow", "Shop Selectors"))
        self.shopTypesCheckBox.setToolTip(_translate("MainWindow", "Enables all shop types."))
        self.shopTypesCheckBox.setText(_translate("MainWindow", "All shop types"))
        self.label_4.setText(_translate("MainWindow", "Or, select from the dropdown below:"))
        self.shopTypesComboBox.setToolTip(_translate("MainWindow", "Selects just one shop type."))
        self.shopTypesComboBox.setItemText(0, _translate("MainWindow", "supermarket"))
        self.shopTypesComboBox.setItemText(1, _translate("MainWindow", "convenience"))
        self.shopTypesComboBox.setItemText(2, _translate("MainWindow", "clothes"))
        self.shopTypesComboBox.setItemText(3, _translate("MainWindow", "bakery"))
        self.outputGB.setTitle(_translate("MainWindow", "Output Options"))
        self.outputShapefileLE.setToolTip(_translate("MainWindow", "Open the dialoge to save the output."))
        self.outputShapefileTB.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Output shapefile"))
        self.startPB.setToolTip(_translate("MainWindow", "Starts the geoprocessing. Dont click this until you are ready!"))
        self.startPB.setText(_translate("MainWindow", "Start"))
        self.actionDisable.setText(_translate("MainWindow", "Disable"))
        self.actionDisable.setToolTip(_translate("MainWindow", "This disables the selection dropdown"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

